version: "3.8"

services:
  prediction-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    expose:
      - 5000
    privileged: true
    environment:
      - SOCKET_HOST="localhost"
      - SOCKET_PORT=5000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  selfplay-client:
    build:
      context: .
      dockerfile: Dockerfile.client
    environment:
      - SOCKET_HOST="prediction-server"
      - SOCKET_PORT=5000
    volumes:
      - ./memory:/memory
    depends_on:
      - prediction-server
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
